#!/usr/bin/env bash
# Helpers for writing source-able .env files safely, even when values contain $, quotes, spaces, etc.
set -Eeuo pipefail

_env_quote() {
  printf '%q' "$1"
}

write_env_line() {
  local key="$1" value="${2-}"
  printf '%s=%s\n' "$key" "$(_env_quote "$value")"
}

write_env_header() {
  printf '# Generated by Homelab v3.1. Do not commit this file.\n'
  printf '# Created: %s\n' "$(date -Is)"
}
